version: 1.0

logmel:
  n_mels: 100
  sampling_rate: 24000
  n_fft: 1024
  hop_size: 256
  max: 2.5
  min: -12

unet:
  dim_base: 256
  use_embed: False
  dim_embed: None
  use_ref_t: False
  dim_cond: 128
  dim_mults: [1, 2, 4]
  pitch_type: log

ddpm:
  num_train_steps: 1000
  inference_steps: 100
  eta: 0.8

  
